### ISSUE TITLE
Spaces in country icon files lead to warning "gtk-update-icon-cache: The generated cache was invalid." on every update.

### ISSUE THREAD

**Issue by GenericUser584** [sunwxg/zypp-gui#3]
Some of the icon files have spaces in them, e.g. `hong kong.png`.

After installing zypp-gui, whenever I perform updates, some updated packages will give these outputs:
`Additional rpm output:
gtk-update-icon-cache: The generated cache was invalid.
warning: %filetriggerin(gtk3-tools-3.24.30-2.3.x86_64) scriptlet failed, exit status 1`.

The error is usually due to icon files having spaces in the filenames. I believe the solution would be to replace all spaces with hyphens or underscores or something (e.g. `hong_kong.png`). After checking my system the only source of icon files with spaces are from this app (only in `/usr/share/icons/hicolor/16x16/places`).

This is not a serious error (doesn't affect normal use), just a bit annoying to see this message appears whenever an updated package triggers an icon cache refresh. Looking forward to see this getting fixed. Thanks.

**Comment by sunwxg** [comment]
Thanks for reporting the issue, I will look into it.
